default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: alba_development
  host: localhost
  port: 3306
  username: root
  password:

test:
  <<: *default
  database: alba_test

production:
  <<: *default
  database: alba_production
