default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/dev_adventures_development

test:
  <<: *default
  database: db/dev_adventures_test

production:
  <<: *default
  database: db/dev_adventures_production
