default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: alba_development

test:
  <<: *default
  database: alba_test

production:
  <<: *default
  database: alba_production
